### ISSUE TITLE
Skip js files

### ISSUE THREAD

**Issue by 810** [PHPCompatibility/PHPCompatibilityJoomla#5]
I got some warnings that the minified js aren't checked. 

We should skip all js

**Comment by mbabker** [comment]
This ruleset isn't specifying paths for exclusion, you need to do that in your local project ruleset (see https://github.com/joomla/cms-coding-standards/blob/master/lib/Joomla-CMS/ruleset.xml as an example).

**Comment by jrfnl** [comment]
@810 FYI: You can also specify only to sniff PHP files from the command line without using a custom ruleset.
Just add `--extensions=php`.

Hope that helps.

@mbabker Should the readme be adjusted to mention this ?

**Comment by mbabker** [comment]
Probably a good idea to mention that in both this and the WordPress ruleset README's, since PHPCS can do some sniffs on non-PHP files and in CMS projects it's pretty common to have PHP and non-PHP files mixed in the same paths.

**Comment by jrfnl** [comment]
@mbabker The thing is, PHPCS itself operates on, and has sniffs for, PHP, JS and CSS.
It's generally just minified JS and CSS files which throw the tokenizer in a spin. It's not something which is specific to the PHPCompatibility standard, though if the PHPCompatibility run is not combined with CS checks, limiting it to PHP files will prevent the issue and make the run faster.

**Comment by jrfnl** [comment]
FYI: PR #8 includes the additional readme section as discussed in this issue.
